### ISSUE TITLE
UnexpectedEmptyPageError and associated errorscre

### ISSUE THREAD

**Issue by robisen1** [jannisborn/paperscraper#31] opened 2023-06-29 05:58 UTC
Please excuse me if I do this incorrectly. I a noob. I am using python 3.11  on Windows 11 and Ubuntu 22.04.2. on  I have run into an error like this on arxiv as well as medarxiv:

arxiv.arxiv.UnexpectedEmptyPageError: Page of results was unexpectedly empty (http://export.arxiv.org/api/query?search_query=%28all%3Apyschological+flow+state%29&id_list=&sortBy=relevance&sortOrder=descending&start=29500&max_results=100)

this seems to be an issue in the original code and was patched here https://github.com/lukasschwab/arxiv.py/issues/43

I did not see that and I took a similar path. My code can checks to see if a URL is malformed or is empty. It handles it and logs it. If it runs into a URL that is not responding or hangs it waits some user-defined amount of time and moves on. You can also make it create smaller jsonl for various reasons. I was also going to implement querying by date. Right now it's all hardcoded variables but I was thinking I should make it so that you can call the options from the command line or a config file. I am also thinking about multi-threaded and being able to throttle your calls to service and or a back-off algorithm. I don't know what I am supposed to do. Do I provide my fixes, if needed, and how or do I go to the arxiv team? I also think these issues lurk in other libraries but I have not made anything like extensive testing. Thank you I appreciate your time and paper scraper.

**Comment by jannisborn** [comment] 2023-07-10 10:46
Hi @robisen1,
thanks for the interest and opening this issue.
Which version of `paperscraper` and `arxiv` are you using respectively?

The root of this problem lies in the arxiv API which is used from the `arxiv` package, so it's not directly related to this package. So it's a bit unclear what you expect from the `paperscraper` team to do here. Please specify. If you have local changes that are fixing some problems, feel free to open a PR

**Comment by jannisborn** [comment] 2023-07-10 20:34
Closing this here, but please comment below if you expect anything to happen from our side.

**Comment by robisen1** [comment] 2023-07-10 20:53
Sorry I am on a plane. I will try to comment on the next two days. Thank you

**Comment by copperwiring** [comment] 2024-08-16 09:22
Hi, I have the same issue:

`raise UnexpectedEmptyPageError(url, try_index, feed)`

Can the code have somewhere if this is returned it just skips and continues and goes to next fetching of data?

**Comment by jannisborn** [comment] 2024-08-16 09:29
Hi,
First, can you please post your full error log, ideally with the query that produced it?
Which version do you use?

Since this is an issue from the `arxiv` package, have you opened an issue there? The fix done in https://github.com/lukasschwab/arxiv.py/issues/43 is available through paperscraper since years. Does this error happen regularly or just occasionally?

**Closed** 2024-08-19 10:30 UTC
Labels: question

**Comment by xqyww123** [comment] 2025-03-09 05:58
Version: 0.2.16

Source to reproduce the issue
```python
from paperscraper.arxiv import get_and_dump_arxiv_papers
query = [['neural theorem prover', 'neural theorem proving']]
get_and_dump_arxiv_papers(query, 'neural-arxiv.jsonl')
```

Full error message:

```
Processing (all:neural theorem prover OR all:neural theorem proving): 301it [00:20, 16.56it[/s](http://localhost:8888/s)]
WARNING:arxiv:Bozo feed; consider handling: document declared as utf-8, but parsed as MacRoman
Processing (all:neural theorem prover OR all:neural theorem proving): 1000it [01:42,  9.75it[/s](http://localhost:8888/s)]
---------------------------------------------------------------------------
UnexpectedEmptyPageError                  Traceback (most recent call last)
File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=625), in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
File ~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626, in Client._parse_feed(self, url, first_page, _try_index)
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)

During handling of the above exception, another exception occurred:

UnexpectedEmptyPageError                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 get_and_dump_arxiv_papers(query, 'neural-arxiv.jsonl')

File ~/.local/lib/python3.12/site-packages/paperscraper/arxiv/arxiv.py:172, in get_and_dump_arxiv_papers(keywords, output_filepath, fields, start_date, end_date, backend, *args, **kwargs)
    169     backend = infer_backend()
    171 if backend == "api":
--> 172     papers = get_arxiv_papers_api(query, fields, *args, **kwargs)
    173 elif backend == "local":
    174     papers = get_arxiv_papers_local(keywords, fields, *args, **kwargs)

File [~/.local/lib/python3.12/site-packages/paperscraper/arxiv/arxiv.py:124](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/paperscraper/arxiv/arxiv.py#line=123), in get_arxiv_papers_api(query, fields, max_results, client_options, search_options, verbose)
    112 search = arxiv.Search(query=query, max_results=max_results, **search_options)
    113 results = client.results(search)
    115 processed = pd.DataFrame(
    116     [
    117         {
    118             arxiv_field_mapper.get(key, key): process_fields.get(
    119                 arxiv_field_mapper.get(key, key), lambda x: x
    120             )(value)
    121             for key, value in vars(paper).items()
    122             if arxiv_field_mapper.get(key, key) in fields and key != "doi"
    123         }
--> 124         for paper in tqdm(results, desc=f"Processing {query}", disable=not verbose)
    125     ]
    126 )
    127 return processed

File [~/.local/lib/python3.12/site-packages/tqdm/std.py:1181](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/tqdm/std.py#line=1180), in tqdm.__iter__(self)
   1178 time = self._time
   1180 try:
-> 1181     for obj in iterable:
   1182         yield obj
   1183         # Update and possibly print the progressbar.
   1184         # Note: does not call self.update(1) for speed optimisation.

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:600](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=599), in Client._results(self, search, offset)
    598     break
    599 page_url = self._format_url(search, offset, self.page_size)
--> 600 feed = self._parse_feed(page_url, first_page=False)

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:634](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=633), in Client._parse_feed(self, url, first_page, _try_index)
    632 if _try_index < self.num_retries:
    633     logger.debug("Got error (try %d): %s", _try_index, err)
--> 634     return self._parse_feed(url, first_page=first_page, _try_index=_try_index + 1)
    635 logger.debug("Giving up (try %d): %s", _try_index, err)
    636 raise err

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:634](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=633), in Client._parse_feed(self, url, first_page, _try_index)
    632 if _try_index < self.num_retries:
    633     logger.debug("Got error (try %d): %s", _try_index, err)
--> 634     return self._parse_feed(url, first_page=first_page, _try_index=_try_index + 1)
    635 logger.debug("Giving up (try %d): %s", _try_index, err)
    636 raise err

    [... skipping similar frames: Client._parse_feed at line 634 (7 times)]

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:634](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=633), in Client._parse_feed(self, url, first_page, _try_index)
    632 if _try_index < self.num_retries:
    633     logger.debug("Got error (try %d): %s", _try_index, err)
--> 634     return self._parse_feed(url, first_page=first_page, _try_index=_try_index + 1)
    635 logger.debug("Giving up (try %d): %s", _try_index, err)
    636 raise err

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:636](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=635), in Client._parse_feed(self, url, first_page, _try_index)
    634     return self._parse_feed(url, first_page=first_page, _try_index=_try_index + 1)
    635 logger.debug("Giving up (try %d): %s", _try_index, err)
--> 636 raise err

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:626](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=625), in Client._parse_feed(self, url, first_page, _try_index)
    619 """
    620 Fetches the specified URL and parses it with feedparser.
    621 
    622 If a request fails or is unexpectedly empty, retries the request up to
    623 `self.num_retries` times.
    624 """
    625 try:
--> 626     return self.__try_parse_feed(url, first_page=first_page, try_index=_try_index)
    627 except (
    628     HTTPError,
    629     UnexpectedEmptyPageError,
    630     requests.exceptions.ConnectionError,
    631 ) as err:
    632     if _try_index < self.num_retries:

File [~/.local/lib/python3.12/site-packages/arxiv/__init__.py:667](http://localhost:8888/home/xero/.local/lib/python3.12/site-packages/arxiv/__init__.py#line=666), in Client.__try_parse_feed(self, url, first_page, try_index)
    665 feed = feedparser.parse(resp.content)
    666 if len(feed.entries) == 0 and not first_page:
--> 667     raise UnexpectedEmptyPageError(url, try_index, feed)
    669 if feed.bozo:
    670     logger.warning(
    671         "Bozo feed; consider handling: %s",
    672         feed.bozo_exception if "bozo_exception" in feed else None,
    673     )

UnexpectedEmptyPageError: Page of results was unexpectedly empty (https://export.arxiv.org/api/query?search_query=%28all%3Aneural+theorem+prover+OR+all%3Aneural+theorem+proving%29&id_list=&sortBy=relevance&sortOrder=descending&start=1000&max_results=100)
```

**Comment by jannisborn** [comment] 2025-03-09 08:55
HI @xqyww123 ,

Thanks for reporting. Unfortunately this is a known issue that may occur. It's not a problem of `paperscraper` but originates from the arXiv API, which is known to be flaky. The right place to discuss such errors is the `arxiv` package on which `paperscraper` depends. You can see this also from the error trace. The discussion related to your problem is here: https://github.com/lukasschwab/arxiv.py/issues/129

You may want to check whether you have an `arxiv` version >= 2 locally to ensure you have the most version for handling arxiv API. Otherwise I dont see much we can do.

Also, I cant reproduce your issue, it's still progressing fine. It depends a bit on your throughput I reckon
```sh
(base) ➜  paperscraper git:(main) ✗ python debug.py
INFO:paperscraper.load_dumps:Loaded biorxiv dump with 363379 entries
INFO:paperscraper.load_dumps:Loaded chemrxiv dump with 28622 entries
INFO:paperscraper.load_dumps:Loaded medrxiv dump with 77788 entries
0.2.16
Processing (all:neural theorem prover OR all:neural theorem proving): 301it [00:15, 20.90it/s]WARNING:arxiv:Bozo feed; consider handling: document declared as utf-8, but parsed as MacRoman
Processing (all:neural theorem prover OR all:neural theorem proving): 7201it [09:36, 12.70it/s]
```
